### ISSUE TITLE
iPhone not always syncing notes with gmail account

### ISSUE THREAD

**Issue by brampauwelyn** [theraspberryguy/SiriControl-System#7]
First of all I want to say that I'm in love with your SiriControl-system.
It's genius! There are so many possibilities. I already have plenty ideas in my head.

I just encounter a small problem with the synchronisation of my notes.
My iPhone doesn't always sync my notes to my gmail account.
When I delete my gmail account and reconfigure my gmail account on my iPhone it works again.

iPhone 6s
11.0.3

Thank you for your reply

**Comment by theraspberryguy** [comment]
That is great to hear! Unfortunately, I do not think there is a solution to this problem as it depends on syncing process. I found that it happens randomly, but has been working for a few weeks now but hopefully, a future update will fix this issue. 

Good luck with your projects.
